package com.chargehub.dao;

import com.chargehub.util.DBConnection;
import java.sql.*;
import java.util.*;

/**
 * Data Access Object (DAO) for managing {@link User} entities.
 *
 * <p>Provides full CRUD operations for user accounts, including role-scoped queries,
 * multiple update strategies, and account status management.</p>
 *
 * <p>Passwords are never stored in plain text — only pre-hashed values via
 * {@link User#getPasswordHash()} are persisted. Callers are responsible for
 * hashing passwords before passing them to any method in this DAO.</p>
 *
 * <p>All database connections are obtained via {@link DBConnection#getConnection()}
 * and are closed automatically using try-with-resources.</p>
 *
 * <p>Author: Minma Rai</p>
 */
public class UserDAO {

    /**
     * Maps a {@link ResultSet} row to a fully populated {@link User} object.
     *
     * @param rs the {@link ResultSet} positioned at the current row
     * @return a {@link User} instance with all fields populated
     * @throws SQLException if any column cannot be read from the result set
     */
    private User map(ResultSet rs) throws SQLException {
        User u = new User();
        u.setUserId(rs.getInt("user_id"));
        u.setFullName(rs.getString("full_name"));
        u.setEmail(rs.getString("email"));
        u.setPhone(rs.getString("phone"));
        u.setPasswordHash(rs.getString("password_hash"));
        u.setVehicleNumber(rs.getString("vehicle_number"));
        u.setAddress(rs.getString("address"));
        u.setRole(rs.getString("role"));
        u.setStatus(rs.getString("status"));
        return u;
    }

    /**
     * Inserts a new user record into the {@code users} table.
     *
     * <p>Use {@link #registerAndGetId(User)} instead if the auto-generated
     * {@code user_id} is needed immediately after insertion.</p>
     *
     * <p>The {@code userId} field on the provided {@link User} object is ignored,
     * as it is auto-generated by the database.</p>
     *
     * @param user the {@link User} object containing all registration fields:
     *             full name, email, phone, password hash, vehicle number,
     *             address, role, and status
     * @return {@code true} if the user was successfully inserted; {@code false} otherwise
     */
    public boolean register(User user) {
        String sql = "INSERT INTO users(full_name, email, phone, password_hash, vehicle_number, " +
                "address, role, status) VALUES(?, ?, ?, ?, ?, ?, ?, ?)";
        try (Connection c = DBConnection.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, user.getFullName());
            ps.setString(2, user.getEmail());
            ps.setString(3, user.getPhone());
            ps.setString(4, user.getPasswordHash());
            ps.setString(5, user.getVehicleNumber());
            ps.setString(6, user.getAddress());
            ps.setString(7, user.getRole());
            ps.setString(8, user.getStatus());
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * Inserts a new user record and returns the auto-generated {@code user_id}.
     *
     * <p>Uses {@link Statement#RETURN_GENERATED_KEYS} to retrieve the database-assigned
     * primary key immediately after insertion. Prefer this over {@link #register(User)}
     * when the new user's ID is needed in the same request, such as for session
     * initialization or immediate follow-up queries.</p>
     *
     * <p>The {@code userId} field on the provided {@link User} object is ignored,
     * as it is auto-generated by the database.</p>
     *
     * @param user the {@link User} object containing all registration fields:
     *             full name, email, phone, password hash, vehicle number,
     *             address, role, and status
     * @return the auto-generated {@code user_id} if insertion was successful;
     *         {@code 0} if the insert failed or no generated key was returned
     */
    public int registerAndGetId(User user) {
        String sql = "INSERT INTO users(full_name, email, phone, password_hash, vehicle_number, " +
                "address, role, status) VALUES(?, ?, ?, ?, ?, ?, ?, ?)";
        try (Connection c = DBConnection.getConnection();
             PreparedStatement ps = c.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, user.getFullName());
            ps.setString(2, user.getEmail());
            ps.setString(3, user.getPhone());
            ps.setString(4, user.getPasswordHash());
            ps.setString(5, user.getVehicleNumber());
            ps.setString(6, user.getAddress());
            ps.setString(7, user.getRole());
            ps.setString(8, user.getStatus());
            if (ps.executeUpdate() > 0) {
                ResultSet rs = ps.getGeneratedKeys();
                if (rs.next()) return rs.getInt(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return 0;
    }

    /**
     * Finds a user by their email address using a case-insensitive comparison.
     *
     * <p>The email is trimmed of leading and trailing whitespace before querying.
     * A {@code null} email is treated as an empty string, which will not match
     * any existing record.</p>
     *
     * <p>Primarily used during authentication to look up a user before
     * verifying their password hash.</p>
     *
     * @param email the email address to search for; may be {@code null}
     * @return the matching {@link User}, or {@code null} if no user is found
     */
    public User findByEmail(String email) {
        String sql = "SELECT * FROM users WHERE LOWER(email) = LOWER(?)";
        try (Connection c = DBConnection.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, email == null ? "" : email.trim());
            ResultSet rs = ps.executeQuery();
            if (rs.next()) return map(rs);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * Finds a single user by their unique ID.
     *
     * @param id the user ID to search for
     * @return the matching {@link User}, or {@code null} if not found
     */
    public User findById(int id) {
        try (Connection c = DBConnection.getConnection();
             PreparedStatement ps = c.prepareStatement(
                     "SELECT * FROM users WHERE user_id=?")) {
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) return map(rs);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * Retrieves all users from the database regardless of role,
     * ordered by user ID descending.
     *
     * <p>This is a convenience wrapper for {@link #findByRole(String)}
     * called with {@code null}.</p>
     *
     * @return a {@link List} of all {@link User} objects; empty list if none found
     */
    public List<User> findAll() {
        return findByRole(null);
    }

    /**
     * Retrieves all users, optionally filtered by role, ordered by user ID descending.
     *
     * <p>When {@code role} is {@code null}, all users are returned regardless of role.
     * This dual behaviour allows {@link #findAll()} to reuse this method without
     * duplicating query logic.</p>
     *
     * <p>Common role values include {@code "admin"}, {@code "manager"},
     * and {@code "user"}.</p>
     *
     * @param role the role to filter by, or {@code null} to return all users
     * @return a {@link List} of {@link User} objects matching the given role;
     *         empty list if none found or an error occurs
     */
    public List<User> findByRole(String role) {
        List<User> list = new ArrayList<>();
        String sql = role == null
                ? "SELECT * FROM users ORDER BY user_id DESC"
                : "SELECT * FROM users WHERE role=? ORDER BY user_id DESC";
        try (Connection c = DBConnection.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            if (role != null) ps.setString(1, role);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) list.add(map(rs));
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return list;
    }

    /**
     * Updates a user's profile and account fields, excluding the password hash.
     *
     * <p>Use this method for administrative updates where the password should
     * not be changed. Use {@link #updateWithPassword(User)} when a password
     * reset or change is also required in the same operation.</p>
     *
     * <p>Fields updated: {@code full_name}, {@code email}, {@code phone},
     * {@code vehicle_number}, {@code address}, {@code role}, {@code status}.</p>
     *
     * @param u the {@link User} object containing updated field values and a valid user ID
     * @return {@code true} if the update affected at least one row; {@code false} otherwise
     */
    public boolean update(User u) {
        String sql = "UPDATE users SET full_name=?, email=?, phone=?, vehicle_number=?, " +
                "address=?, role=?, status=? WHERE user_id=?";
        try (Connection c = DBConnection.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, u.getFullName());
            ps.setString(2, u.getEmail());
            ps.setString(3, u.getPhone());
            ps.setString(4, u.getVehicleNumber());
            ps.setString(5, u.getAddress());
            ps.setString(6, u.getRole());
            ps.setString(7, u.getStatus());
            ps.setInt(8, u.getUserId());
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * Updates all user fields including the password hash in a single operation.
     *
     * <p>Use this method when a password change is required alongside other field
     * updates, such as during an admin-initiated password reset. For updates that
     * should not touch the password, use {@link #update(User)} instead.</p>
     *
     * <p>Fields updated: {@code full_name}, {@code email}, {@code phone},
     * {@code vehicle_number}, {@code address}, {@code role}, {@code status},
     * {@code password_hash}.</p>
     *
     * <p><strong>Note:</strong> The caller is responsible for ensuring that
     * {@link User#getPasswordHash()} contains a properly hashed value before
     * invoking this method. Plain text passwords must never be passed here.</p>
     *
     * @param u the {@link User} object containing all updated fields including
     *          a valid hashed password and a valid user ID
     * @return {@code true} if the update affected at least one row; {@code false} otherwise
     */
    public boolean updateWithPassword(User u) {
        String sql = "UPDATE users SET full_name=?, email=?, phone=?, vehicle_number=?, " +
                "address=?, role=?, status=?, password_hash=? WHERE user_id=?";
        try (Connection c = DBConnection.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, u.getFullName());
            ps.setString(2, u.getEmail());
            ps.setString(3, u.getPhone());
            ps.setString(4, u.getVehicleNumber());
            ps.setString(5, u.getAddress());
            ps.setString(6, u.getRole());
            ps.setString(7, u.getStatus());
            ps.setString(8, u.getPasswordHash());
            ps.setInt(9, u.getUserId());
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * Updates only the self-editable profile fields for a user.
     *
     * <p>Intentionally excludes sensitive fields such as {@code email},
     * {@code role}, {@code status}, and {@code password_hash}, making it
     * safe for use in user-facing profile edit forms where those fields
     * must not be user-modifiable.</p>
     *
     * <p>Fields updated: {@code full_name}, {@code phone},
     * {@code vehicle_number}, {@code address}.</p>
     *
     * @param u the {@link User} object containing the updated profile fields
     *          and a valid user ID
     * @return {@code true} if the update affected at least one row; {@code false} otherwise
     */
    public boolean updateProfile(User u) {
        String sql = "UPDATE users SET full_name=?, phone=?, vehicle_number=?, address=? " +
                "WHERE user_id=?";
        try (Connection c = DBConnection.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, u.getFullName());
            ps.setString(2, u.getPhone());
            ps.setString(3, u.getVehicleNumber());
            ps.setString(4, u.getAddress());
            ps.setInt(5, u.getUserId());
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * Updates self-editable profile fields including the email address.
     *
     * <p>This is an extended variant of {@link #updateProfile(User)} that also
     * permits the email address to be changed. Use this only in flows where
     * email modification has been explicitly permitted and validated — for example,
     * after a successful email-verification step — since email is otherwise
     * treated as a non-user-modifiable field.</p>
     *
     * <p>Fields updated: {@code full_name}, {@code email}, {@code phone},
     * {@code vehicle_number}, {@code address}.</p>
     *
     * <p>Fields intentionally excluded: {@code role}, {@code status},
     * {@code password_hash}.</p>
     *
     * @param u the {@link User} object containing the updated profile fields
     *          including the new email address, and a valid user ID
     * @return {@code true} if the update affected at least one row; {@code false} otherwise
     */
    public boolean updateProfileWithEmail(User u) {
        String sql = "UPDATE users SET full_name=?, email=?, phone=?, vehicle_number=?, address=? " +
                "WHERE user_id=?";
        try (Connection c = DBConnection.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, u.getFullName());
            ps.setString(2, u.getEmail());
            ps.setString(3, u.getPhone());
            ps.setString(4, u.getVehicleNumber());
            ps.setString(5, u.getAddress());
            ps.setInt(6, u.getUserId());
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * Updates only the password hash for a specific user.
     *
     * <p>Use this method for standalone password change or reset flows where
     * no other user fields need to be modified. For a combined profile-and-password
     * update in a single operation, use {@link #updateWithPassword(User)} instead.</p>
     *
     * <p><strong>Note:</strong> The caller is responsible for ensuring that
     * {@code passwordHash} contains a properly hashed value before invoking
     * this method. Plain text passwords must never be passed here.</p>
     *
     * @param userId       the unique ID of the user whose password hash is to be updated
     * @param passwordHash the new hashed password to persist; must not be plain text
     * @return {@code true} if the update affected at least one row; {@code false} otherwise
     */
    public boolean updatePasswordHash(int userId, String passwordHash) {
        try (Connection c = DBConnection.getConnection();
             PreparedStatement ps = c.prepareStatement(
                     "UPDATE users SET password_hash=? WHERE user_id=?")) {
            ps.setString(1, passwordHash);
            ps.setInt(2, userId);
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * Updates only the account status of a specific user.
     *
     * <p>Common status values include {@code "active"} and {@code "inactive"}.
     * Prefer this method over {@link #update(User)} when only the account
     * status needs to change, to avoid binding all other user fields.</p>
     *
     * @param id     the unique ID of the user whose status is to be updated
     * @param status the new account status to apply
     * @return {@code true} if the update affected at least one row; {@code false} otherwise
     */
    public boolean changeStatus(int id, String status) {
        try (Connection c = DBConnection.getConnection();
             PreparedStatement ps = c.prepareStatement(
                     "UPDATE users SET status=? WHERE user_id=?")) {
            ps.setString(1, status);
            ps.setInt(2, id);
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * Permanently deletes a user record from the database.
     *
     * <p><strong>Note:</strong> This operation is irreversible. Deleting a user
     * that is referenced by existing bookings, payments, reviews, or favourites
     * may violate foreign key constraints depending on the database schema configuration.</p>
     *
     * @param id the unique ID of the user to delete
     * @return {@code true} if the deletion was successful; {@code false} if no record
     *         was found with the given ID or an error occurs
     */
    public boolean delete(int id) {
        try (Connection c = DBConnection.getConnection();
             PreparedStatement ps = c.prepareStatement(
                     "DELETE FROM users WHERE user_id=?")) {
            ps.setInt(1, id);
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * Returns the total number of users, optionally filtered by role.
     *
     * <p>When {@code role} is {@code null}, the count includes all users
     * regardless of role. This mirrors the dual behaviour of {@link #findByRole(String)}.</p>
     *
     * <p>Common role values include {@code "admin"}, {@code "manager"},
     * and {@code "user"}.</p>
     *
     * @param role the role to filter by, or {@code null} to count all users
     * @return the number of users matching the given role, or the total user count
     *         if {@code role} is {@code null}; returns {@code 0} on error
     */
    public int countByRole(String role) {
        String sql = role == null
                ? "SELECT COUNT(*) FROM users"
                : "SELECT COUNT(*) FROM users WHERE role=?";
        try (Connection c = DBConnection.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            if (role != null) ps.setString(1, role);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) return rs.getInt(1);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return 0;
    }

    /**
     * Returns the count of active EV owner accounts.
     *
     * <p>Counts only users whose {@code role} is {@code "user"} and whose
     * {@code status} is {@code "active"}, using case-insensitive, whitespace-trimmed
     * comparisons to guard against minor data inconsistencies stored in the database.</p>
     *
     * <p>This is a narrower alternative to {@link #countByRole(String)} — it combines
     * both a role filter and a status filter in a single query, making it suitable
     * for dashboard metrics that need to reflect only currently active EV owners.</p>
     *
     * @return the number of active EV owner accounts; {@code 0} on error or if none found
     */
    public int countActiveEvOwners() {
        String sql = "SELECT COUNT(*) FROM users WHERE LOWER(TRIM(role))='user' AND LOWER(TRIM(status))='active'";
        try (Connection c = DBConnection.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ResultSet rs = ps.executeQuery();
            if (rs.next()) return rs.getInt(1);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return 0;
    }
}
